### PR TITLE
Refix undefined name now that tests are passing

### PR DESCRIPTION
**Pull request by cclauss**
Redo of #4

### CODE REVIEW

**Comment by njdreikosen** [comment]
The Travis CI checks are still failing, let me poke around and see if I can figure out what's going wrong.

**Comment by njdreikosen** [comment]
It looks like Travis CI changed their pricing model, so I need to figure out how to migrate to the new free OSS settings and then I can resume trying to get the checks to pass

**Comment by njdreikosen** [comment]
Looks like the environment variables weren't useable for some reason when you tried to push to the repo, so I updated some settings and moved the env variables. You'll have to pull in the changes (should only be changes to .travis.yml), that way when you try and push your changes again the Travis CI settings will be updated.

**Comment by cclauss** [comment]
Perhaps it is just easier if you make this change on you side.  Thanks.

**Pull request closed without merging**
